### ISSUE TITLE
install.sh verify-install step does not honor ${CFG_DESTDIR}

### ISSUE THREAD

**Issue by gbsf** [rust-lang/rust-installer#15]
At [install-template.sh:724-725](https://github.com/rust-lang/rust-installer/blob/1323aeb86cc6158a4a1c9895aa48439f7fbe8c6b/install-template.sh#L724-L725), the script tries to run the binaries without taking in consideration the destination dir.
Thus, running `make DESTDIR=… install` will always fail. I also couldn't find a `--disable-verify-install` switch to `make install`, as the error message says.

As an aside, the comment above that block also needs changing.

**Comment by brson** [comment]
Thanks for the report! I'm spending some time on rust-installer this week and will try to get this fixed soon.

**Comment by brson** [comment]
Fix is on my 'next' branch. Will take a week or two to find its way into rust.

**Comment by brson** [comment]
`install.sh --help` shows the `--disable-verify` option for me.

**Comment by gbsf** [comment]
I was running `make install` on the rust repo, so I had no way to manually invoke install.sh.
In any case, I found the `--disable-verify-install` switch. But it is in `./configure`, not in `make install` like the error message says.
