### ISSUE TITLE
Manifests contain backslashes when built on windows

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust-installer#65]
This results in windows targets being uninstallable on linux with the latest nightly.

Paths should be converted to a platform independent format before being written to the manifest: https://github.com/rust-lang/rust-installer/blob/master/src/generator.rs#L120-L124

**Comment by cuviper** [comment]
Ah, I see.  I dealt with that for tar itself (alexcrichton/tar-rs#106), but I neglected to check the manifest.
