### ISSUE TITLE
newest installer.sh of rust-src used \r\n to end lines

### ISSUE THREAD

**Issue by contrun** [rust-lang/rust-installer#95]
I obtained the newest rust-src using
```
wget https://static.rust-lang.org/dist/2019-06-30/rust-src-nightly.tar.gz
```
The installer.sh wthin this tarball used `\r\n` to end lines.

![screenshot-2019-06-30-22-03-41](https://user-images.githubusercontent.com/32609395/60397905-bc616a80-9b84-11e9-85c7-c82d9d98e1c7.png)

I can only find relevant code in this repo,  but the `install-template.sh` of this repo ends line correctly. Don't know how that happened.

**Comment by pietroalbini** [comment]
This is not caused by this repo but by rust-lang/rust's CI. Closing in favor of https://github.com/rust-lang/rust/issues/62276.
